name: Linux (CUDA, devel)

on:
  schedule:
    - cron: "00 7 * * *" # runs at 07:00 UTC/12:00 PST every day
  workflow_dispatch:
    inputs:
      version:
        description: "latest/stable/sem_ver"
        required: true
        default: "latest"
        type: string
      branch:
        description: "branch name"
        required: true
        default: "main"
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        cuda-version: ["11"]

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./docker/optional
          push: true
          tags: scverse/scvi-tools:py${{ matrix.python-version }}-cu${{ matrix.cuda-version }}-devel-${{ inputs.scvi-tools-version }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
            SCVI_TOOLS_VERSION=${{ inputs.scvi-tools-version }}
            BRANCH_NAME=${{ inputs.branch }}
            DEPENDENCIES=dev
