name: linux (cuda, base)

on:
  schedule:
    - cron: "0 7 * * 0" # runs at 07:00 UTC/12:00 PST on Sunday
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"]
        cuda: ["11", "12"]
        version: ["cuda"]
        dependencies: ["base"]

    uses: ./.github/workflows/linux_cuda.yaml
    with:
      python: ${{ matrix.python }}
      cuda: ${{ matrix.cuda }}
      version: ${{ matrix.version }}
      dependencies: ${{ matrix.dependencies }}

    secrets: inherit
