name: linux-cuda-base

on:
  schedule:
    - cron: "0 12 * * 0"  # runs at 12:00 UTC -> 05:00 PST on Sunday
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version"
        required: true
        default: "3.11"
        options:
        - "3.9"
        - "3.10"
        - "3.11"
      cuda-version:
        description: "CUDA version"
        required: true
        default: "11"
        options:
        - "11"
        - "12"

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        cuda-version: ["11", "12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/base
          push: true
          tags: scverse/scvi-tools:py${{ matrix.python-version }}-cu${{ matrix.cuda-version }}-base
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
