name: Linux (CUDA, base)

on:
  schedule:
    - cron: "0 7 * * 0" # runs at 07:00 UTC/12:00 PST on Sunday
  workflow_dispatch:

jobs:
  docker:
    runs-on: [self-hosted, Linux, X64, CUDA]
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        cuda-version: ["11"]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./docker/base
          push: true
          tags: scverse/scvi-tools:py${{ matrix.python-version }}-cu${{ matrix.cuda-version }}-base
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
