name: linux (cuda, manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "latest/stable/semver/branch"
        required: true
        default: "latest"
        type: string

      dependencies:
        description: "optional dependencies"
        required: false
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"]
        cuda: ["11", "12"]

    uses: ./.github/workflows/linux_cuda.yaml
    with:
      python: ${{ matrix.python }}
      cuda: ${{ matrix.cuda }}
      version: ${{ inputs.version }}
      dependencies: ${{ inputs.dependencies }}

    secrets: inherit
