ame: Linux (CUDA, latest)

on:
  schedule:
    - cron: "00 7 * * *" # runs at 07:00 UTC/12:00 PST every day
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"]
        cuda: ["11"]
        version: ["latest"]
        dependencies: ["", "dev", "test"]

    uses: ./.github/workflows/linux_cuda.yaml

    secrets: inherit
