name: linux-cuda-runtime

on:
  workflow_dispatch:
    inputs:
      scvi-tools-version:
        description: "scvi-tools version"
        required: true
        default: "stable"
        type: choice
        options:
        - "stable"

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        cuda-version: ["11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./images/linux/cuda/runtime
          push: true
          tags: martinkim0/scvi-tools:py${{ matrix.python-version }}-cu${{ matrix.cuda-version }-devel-${{ inputs.scvi-tools-version}}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
            SCVI_TOOLS_VERSION=${{ inputs.scvi-tools-version}}
